name: NodeJS with Webpack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node_version: ['17.x']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ node-version }}

      - name: Install NPM dependencies
        run: npm install

      - name: Build
        run: npm run build:prod
